version: "3"

services:
    portal:
        depends_on: 
            - httpserver
        image: jcs-portal
        ports:
        - "8080:80"

    httpserver:
        depends_on: 
            - mongo
            - storage-bj
            - storage-sh
            - storage-gz
            - scheduler
        image: jcs-httpserver
        command: -mongo mongodb://mongo:27017 -sched scheduler:5001

    storage-bj:
        depends_on: 
            - minio-bj
        image: jcs-storage
        command: -endpoint minio-bj:9000 -ak=minioadmin -sk=minioadmin

    storage-sh:
        depends_on: 
            - minio-sh
        image: jcs-storage
        command: -endpoint minio-sh:9000 -ak=minioadmin -sk=minioadmin
    
    storage-gz:
        depends_on: 
            - minio-gz
        image: jcs-storage
        command: -endpoint minio-gz:9000 -ak=minioadmin -sk=minioadmin
    
    scheduler:
        image: jcs-scheduler

    mongo:
        image: mongo

    minio-bj:
        image: minio/minio
        command: server /data

    minio-sh:
        image: minio/minio
        command: server /data

    minio-gz:
        image: minio/minio
        command: server /data
