version: "3"

services:
    portal:
        depends_on: 
            - httpserver
        image: harbor.cloudcps.net/library/jcs-portal
        volumes: 
            - ./configs/portal.conf:/etc/nginx/nginx.conf:ro
        ports:
        - "8080:80"

    httpserver:
        depends_on: 
            - mongo
            - storage-bj
            - storage-sh
            - storage-gz
            - scheduler
        image: harbor.cloudcps.net/library/jcs-httpserver
        volumes: 
            - ./configs/httpserver.json:/httpserver/httpserver.json:ro
        command: -mongo=mongodb://mongo:27017 -sched=scheduler:5001 -test

    storage-bj:
        depends_on: 
            - minio-bj
        image: harbor.cloudcps.net/library/jcs-storage
        volumes: 
            - ./configs/storage.json:/storage/storage.json:ro
        command: -endpoint=minio-bj:9000 -ak=minioadmin -sk=minioadmin

    storage-sh:
        depends_on: 
            - minio-sh
        image: harbor.cloudcps.net/library/jcs-storage
        volumes: 
            - ./configs/storage.json:/storage/storage.json:ro
        command: -endpoint=minio-sh:9000 -ak=minioadmin -sk=minioadmin
    storage-gz:
        depends_on: 
            - minio-gz
        image: harbor.cloudcps.net/library/jcs-storage
        volumes: 
            - ./configs/storage.json:/storage/storage.json:ro
        command: -endpoint=minio-gz:9000 -ak=minioadmin -sk=minioadmin
    
    scheduler:
        image: harbor.cloudcps.net/library/jcs-scheduler

    mongo:
        image: mongo

    minio-bj:
        image: minio/minio
        command: server /data

    minio-sh:
        image: minio/minio
        command: server /data

    minio-gz:
        image: minio/minio
        command: server /data
