version: "3"

services:
    portal:
        depends_on: 
            - httpserver
        image: jcs-portal
        volumes: 
            - ./configs/portal.conf:/etc/nginx/nginx.conf:ro
        ports:
        - "8080:80"

    httpserver:
        depends_on: 
            - mongo
            - storage-bj
            - storage-sh
            - storage-gz
            - scheduler
        image: jcs-httpserver
        ports: 
            - 10090:10090
        volumes: 
            - ./configs/httpserver.json:/httpserver/httpserver.json:ro
        command: -mongo=mongodb://mongo:27017 -sched=scheduler:5001 -test

    storage-bj:
        depends_on: 
            - minio-bj
        image: jcs-storage
        volumes: 
            - ./configs/storage.json:/storage/storage.json:ro
        command: -endpoint=minio-bj:9000 -ak=minioadmin -sk=minioadmin

    storage-sh:
        depends_on: 
            - minio-sh
        image: jcs-storage
        volumes: 
            - ./configs/storage.json:/storage/storage.json:ro
        command: -endpoint=minio-sh:9000 -ak=minioadmin -sk=minioadmin
    storage-gz:
        depends_on: 
            - minio-gz
        image: jcs-storage
        volumes: 
            - ./configs/storage.json:/storage/storage.json:ro
        command: -endpoint=minio-gz:9000 -ak=minioadmin -sk=minioadmin
    
    scheduler:
        image: jcs-scheduler

    mongo:
        image: mongo

    minio-bj:
        image: minio/minio
        command: server /data

    minio-sh:
        image: minio/minio
        command: server /data

    minio-gz:
        image: minio/minio
        command: server /data

    prometheus:
        image: prom/prometheus
        volumes:
            - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - /opt/grafana-storage:/var/lib/grafana:rw